application: cycletracks
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /dojango/media/dojango/dojango.js
  static_files: static/dojango.js
  upload: dojango/media/dojango/dojango.js

- url: /dojango/media/dojango/_base.js
  static_files: static/_base.js
  upload: dojango/media/dojango/_base.js

- url: /.*
  script: main.py
  login: required
