application: cycletracks
version: 1
runtime: python
api_version: 1

default_expiration: "2d"

handlers:
- url: /media
  static_dir: _generated_media

- url: /static
  static_dir: static/

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /a/\d+.kml
  script: common/appenginepatch/main.py

- url: /a/\d+.pub
  script: common/appenginepatch/main.py

- url: /a/\d+.data
  script: common/appenginepatch/main.py

- url: /about.*
  script: common/appenginepatch/main.py

- url: /admin/.*
  script: common/appenginepatch/main.py
  login: admin

- url: /.*
  script: common/appenginepatch/main.py
  login: required
