application: cycletracks
version: 1
runtime: python
api_version: 1

default_expiration: "2d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?gcycle/test/.*
- ^(.*/)?gcycle/tests.py
- ^(.*/)?django/bin/.*
- ^(.*/)?django/contrib/admin/.*
- ^(.*/)?django/contrib/admindocs/.*
- ^(.*/)?django/contrib/comments/.*
- ^(.*/)?django/contrib/flatpages/.*
- ^(.*/)?django/contrib/markup/.*
- ^(.*/)?django/contrib/sitemaps/.*
- ^(.*/)?django/contrib/syndication/.*
- ^(.*/)?django/contrib/gis/.*
- ^(.*/)?django/contrib/databrowse/.*
- ^(.*/)?django/contrib/localflavor/.*
- ^(.*/)?django/contrib/csrf/.*
- ^(.*/)?django/conf/locale.*
- .svn


handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /a/\d+.kml
  script: main.py

- url: /a/\d+.pub
  script: main.py

- url: /a/\d+.data
  script: main.py

- url: /about.*
  script: main.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
  login: required
